### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by somehibs** [mikdsouza/MonitorSwitcher#1]
I don't actually have an issue. This is awesome, I use it every day and I wanted to let you know that someone appreciates it! Looks like I'm not alone, there's 300 downloads a week on SourceForge.

The GUI helped me make the XML files quickly, then I use two Windows Shortcut keys for switching between my work/personal profiles. It's perfect!

**Comment by mikdsouza** [comment]
Hey @somehibs, I wrote this app so long ago. Thanks for coming back with feedback, I'm glad you got use out of it!
